modified worflow

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -63,10 +63,27 @@ jobs:
         with:
           name: inventory-tracker-jar  # Match the artifact name used in the build job
 
+      - name: List files in download directory
+        run: ls -la /home/runner/work/InventoryTracker-SpringBoot-Backend/InventoryTracker-SpringBoot-Backend
+
+      - name: Check if .jar file exists
+        run: |
+          if [ ! -f inventory-tracker-jar/inventory-tracker-1.0.jar ]; then
+            echo "Error: .jar file not found!"
+            exit 1
+          fi
+
+      - name: Set up SSH key for deployment
+        run: |
+                echo "$PRIVATE_KEY" > private_key.pem
+                chmod 600 private_key.pem
+              env:
+                PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+
       # Copy the .jar file to the EC2 instance
       - name: Copy .jar file to EC2
         run: |
-          scp -i ${{ secrets.SSH_PRIVATE_KEY }} inventory-tracker-jar/inventory-tracker-1.0.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/inventory-tracker-1.0.jar
+          scp -v -i ${{ secrets.SSH_PRIVATE_KEY }} inventory-tracker-jar/inventory-tracker-1.0.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/inventory-tracker-1.0.jar
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
